'use client';

import { useEffect, useMemo, useState } from 'react';

const sections = [
  ['dashboard','Dashboard'],['customers','Customers'],['pocs','POCs'],['requirements','Requirements'],
  ['environment','Environment'],['entry','Entry Checklist'],['tests','POC Results'],['metrics','Metrics'],
  ['concerns','Client Concerns'],['exit','Exit Checklist'],['signoff','Sign-off']
];
const empty = { customers:[], pocs:[], requirements:[], entry_checklist:[], exit_checklist:[], poc_tests:[], poc_metrics:[], client_concerns:[], poc_signoffs:[] };

export default function Home() {
  const [data,setData]=useState(empty); const [section,setSection]=useState('dashboard'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [search,setSearch]=useState('');
  const [customer,setCustomer]=useState({customer_name:'',industry:'',location:'',primary_contact:'',technical_contact:'',decision_maker:''});
  const [poc,setPoc]=useState({customer_id:'',poc_code:'',status:'Planned',start_date:'',end_date:'',business_objective:'',primary_use_case:'',solution_version:'',poc_environment:''});
  const [selectedPoc,setSelectedPoc]=useState('');
  const [item,setItem]=useState({ requirement:'',business_priority:'Medium',technical_priority:'Medium',acceptance_criteria:'',owner:'' });
  const [concern,setConcern]=useState({concern:'',concern_type:'Technical',impact:'',response_resolution:'',owner:'',status:'Open'});

  async function load(){ setLoading(true); try { const r=await fetch('/api/poc',{cache:'no-store'}); const j=await r.json(); if(!j.ok) throw new Error(j.error); setData(j.data); if(!selectedPoc && j.data.pocs?.[0]) setSelectedPoc(j.data.pocs[0].id); } catch(e){ setMessage('Database error: '+e.message); } finally {setLoading(false);} }
  useEffect(()=>{load()},[]);
  const activePoc=useMemo(()=>data.pocs.find(x=>x.id===selectedPoc)||data.pocs[0], [data.pocs,selectedPoc]);
  const activeCustomer=useMemo(()=>data.customers.find(x=>x.id===activePoc?.customer_id),[data.customers,activePoc]);
  async function insert(table,record,after=load){ setSaving(true); setMessage(''); try { const r=await fetch('/api/poc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,record})}); const j=await r.json(); if(!j.ok) throw new Error(j.error); setMessage('Saved successfully.'); await after(); } catch(e){setMessage('Save failed: '+e.message)} finally{setSaving(false)} }
  async function update(table,id,changes){ try { const r=await fetch('/api/poc',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,id,changes})}); const j=await r.json(); if(!j.ok) throw new Error(j.error); await load(); } catch(e){setMessage('Update failed: '+e.message)} }
  function createCustomer(e){e.preventDefault(); insert('customers',customer,async()=>{await load(); setCustomer({customer_name:'',industry:'',location:'',primary_contact:'',technical_contact:'',decision_maker:''});});}
  function createPoc(e){e.preventDefault(); const code=poc.poc_code || `POC-${new Date().getFullYear()}-${String(data.pocs.length+1).padStart(3,'0')}`; insert('pocs',{...poc,poc_code:code},async()=>{await load();setPoc({...poc,poc_code:''});});}
  function addRequirement(e){e.preventDefault(); if(!activePoc)return setMessage('Select a POC first.'); insert('requirements',{...item,poc_id:activePoc.id},async()=>{await load();setItem({ requirement:'',business_priority:'Medium',technical_priority:'Medium',acceptance_criteria:'',owner:'' });});}
  function addConcern(e){e.preventDefault(); if(!activePoc)return setMessage('Select a POC first.'); insert('client_concerns',{...concern,poc_id:activePoc.id},async()=>{await load();setConcern({concern:'',concern_type:'Technical',impact:'',response_resolution:'',owner:'',status:'Open'});});}
  const filteredCustomers=data.customers.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
  const filteredPocs=data.pocs.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
  const counts={customers:data.customers.length,pocs:data.pocs.length,requirements:data.requirements.length,concerns:data.client_concerns.length};
  return <div className="app"><aside><div className="brand">RESOFTO</div><div className="product">Multi-Seat<br/>Solution</div><div className="nav">{sections.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</div><div className="sidefoot">POC Management & Validation</div></aside><main><header><div><div className="eyebrow">RESOFTO</div><h1>Multi-Seat Solution</h1><p>POC Management & Validation Platform</p></div><div className="actions"><button onClick={()=>location.href='/api/poc/export'}>Export Excel</button><button className="primary" onClick={()=>setSection('pocs')}>+ New POC</button></div></header><div className="content">{message&&<div className="notice">{message}</div>}{loading?<div className="card loading">Loading database…</div>:<>{section==='dashboard'&&<Dashboard counts={counts} data={data} activePoc={activePoc} activeCustomer={activeCustomer} onPoc={setSelectedPoc} onSection={setSection}/>} {section==='customers'&&<Customers data={filteredCustomers} form={customer} setForm={setCustomer} onSubmit={createCustomer}/>} {section==='pocs'&&<POCs data={filteredPocs} customers={data.customers} form={poc} setForm={setPoc} onSubmit={createPoc} selected={selectedPoc} setSelected={setSelectedPoc}/>} {section==='requirements'&&<Requirements data={data.requirements.filter(x=>!activePoc||x.poc_id===activePoc.id)} form={item} setForm={setItem} onSubmit={addRequirement} activePoc={activePoc}/>} {section==='concerns'&&<Concerns data={data.client_concerns.filter(x=>!activePoc||x.poc_id===activePoc.id)} form={concern} setForm={setConcern} onSubmit={addConcern} activePoc={activePoc}/>} {['environment','entry','tests','metrics','exit','signoff'].includes(section)&&<GenericSection section={section} data={data} activePoc={activePoc} update={update}/>}</>}</div></main></div>
}

function Dashboard({counts,data,activePoc,activeCustomer,onPoc,onSection}){return <><div className="cards">{[['Customers',counts.customers],['Active POCs',data.pocs.filter(x=>x.status==='In Progress').length],['Completed POCs',data.pocs.filter(x=>x.status==='Completed').length],['Pending Concerns',data.client_concerns.filter(x=>x.status!=='Resolved').length]].map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="grid2"><div className="card"><div className="cardhead"><h2>POC Workspace</h2><button onClick={()=>onSection('pocs')}>Manage POCs</button></div>{activePoc?<><div className="workspace"><div><label>Customer</label><strong>{activeCustomer?.customer_name||'—'}</strong></div><div><label>POC</label><strong>{activePoc.poc_code}</strong></div><div><label>Status</label><strong>{activePoc.status}</strong></div><div><label>Dates</label><strong>{activePoc.start_date||'—'} → {activePoc.end_date||'—'}</strong></div></div><div className="quick"><button onClick={()=>onSection('requirements')}>Requirements</button><button onClick={()=>onSection('entry')}>Entry Checklist</button><button onClick={()=>onSection('tests')}>Results</button><button onClick={()=>onSection('exit')}>Exit Checklist</button><button onClick={()=>onSection('signoff')}>Sign-off</button></div></>:<p className="muted">Create a POC to begin.</p>}</div><div className="card"><h2>Recent POCs</h2>{data.pocs.slice(-6).reverse().map(p=><button className="listrow" key={p.id} onClick={()=>onPoc(p.id)}><span>{p.poc_code}</span><b>{p.status}</b></button>)}</div></div></>}

function Customers({data,form,setForm,onSubmit}){return <div className="grid2"><FormCard title="Add Customer" onSubmit={onSubmit}><Input label="Customer Name *" value={form.customer_name} onChange={v=>setForm({...form,customer_name:v})}/><Input label="Industry" value={form.industry} onChange={v=>setForm({...form,industry:v})}/><Input label="Location" value={form.location} onChange={v=>setForm({...form,location:v})}/><Input label="Primary Contact" value={form.primary_contact} onChange={v=>setForm({...form,primary_contact:v})}/><Input label="Technical Contact" value={form.technical_contact} onChange={v=>setForm({...form,technical_contact:v})}/><Input label="Decision Maker" value={form.decision_maker} onChange={v=>setForm({...form,decision_maker:v})}/><button className="primary">Save Customer</button></FormCard><div className="card"><h2>Customers</h2>{data.map(x=><div className="tableRow" key={x.id}><b>{x.customer_name}</b><span>{x.industry||'—'}</span><span>{x.location||'—'}</span></div>)}</div></div>}
function POCs({data,customers,form,setForm,onSubmit,selected,setSelected}){return <div className="grid2"><FormCard title="Create POC" onSubmit={onSubmit}><Select label="Customer *" value={form.customer_id} onChange={v=>setForm({...form,customer_id:v})} options={customers.map(x=>[x.id,x.customer_name])}/><Input label="POC Code" placeholder="Auto-generated if blank" value={form.poc_code} onChange={v=>setForm({...form,poc_code:v})}/><Select label="Status" value={form.status} onChange={v=>setForm({...form,status:v})} options={['Planned','In Progress','Completed','On Hold'].map(x=>[x,x])}/><div className="two"><Input type="date" label="Start Date" value={form.start_date} onChange={v=>setForm({...form,start_date:v})}/><Input type="date" label="End Date" value={form.end_date} onChange={v=>setForm({...form,end_date:v})}/></div><Input label="Business Objective" value={form.business_objective} onChange={v=>setForm({...form,business_objective:v})}/><Input label="Primary Use Case" value={form.primary_use_case} onChange={v=>setForm({...form,primary_use_case:v})}/><Input label="Solution Version" value={form.solution_version} onChange={v=>setForm({...form,solution_version:v})}/><Input label="POC Environment" value={form.poc_environment} onChange={v=>setForm({...form,poc_environment:v})}/><button className="primary">Create POC</button></FormCard><div className="card"><h2>POCs</h2>{data.map(p=><button className={'pocrow '+(selected===p.id?'selected':'')} key={p.id} onClick={()=>setSelected(p.id)}><div><b>{p.poc_code}</b><span>{customers.find(c=>c.id===p.customer_id)?.customer_name||'Unknown customer'}</span></div><em>{p.status}</em></button>)}</div></div>}
function Requirements({data,form,setForm,onSubmit,activePoc}){return <div className="grid2"><FormCard title={`Add Requirement ${activePoc?`— ${activePoc.poc_code}`:''}`} onSubmit={onSubmit}><Input label="Requirement *" value={form.requirement} onChange={v=>setForm({...form,requirement:v})}/><Select label="Business Priority" value={form.business_priority} onChange={v=>setForm({...form,business_priority:v})} options={['High','Medium','Low'].map(x=>[x,x])}/><Select label="Technical Priority" value={form.technical_priority} onChange={v=>setForm({...form,technical_priority:v})} options={['High','Medium','Low'].map(x=>[x,x])}/><Input label="Acceptance Criteria" value={form.acceptance_criteria} onChange={v=>setForm({...form,acceptance_criteria:v})}/><Input label="Owner" value={form.owner} onChange={v=>setForm({...form,owner:v})}/><button className="primary">Save Requirement</button></FormCard><ListCard title="Requirements" rows={data} fields={['requirement','business_priority','status']}/></div>}
function Concerns({data,form,setForm,onSubmit,activePoc}){return <div className="grid2"><FormCard title={`Add Client Concern ${activePoc?`— ${activePoc.poc_code}`:''}`} onSubmit={onSubmit}><Input label="Concern *" value={form.concern} onChange={v=>setForm({...form,concern:v})}/><Select label="Type" value={form.concern_type} onChange={v=>setForm({...form,concern_type:v})} options={['Technical','Commercial','Security','Performance','Deployment','Other'].map(x=>[x,x])}/><Input label="Impact" value={form.impact} onChange={v=>setForm({...form,impact:v})}/><Input label="Response / Resolution" value={form.response_resolution} onChange={v=>setForm({...form,response_resolution:v})}/><Input label="Owner" value={form.owner} onChange={v=>setForm({...form,owner:v})}/><Select label="Status" value={form.status} onChange={v=>setForm({...form,status:v})} options={['Open','In Progress','Resolved'].map(x=>[x,x])}/><button className="primary">Save Concern</button></FormCard><ListCard title="Client Concerns" rows={data} fields={['concern','concern_type','status']}/></div>}
function GenericSection({section,data,activePoc,update}){const map={environment:['Customer Environment',data.customers],entry:['Entry Checklist',data.entry_checklist],tests:['POC Results',data.poc_tests],metrics:['Metrics',data.poc_metrics],exit:['Exit Checklist',data.exit_checklist],signoff:['Client Sign-off',data.poc_signoffs]}; const [title,rows]=map[section]; const filtered=rows.filter(x=>!activePoc||x.poc_id===activePoc.id); return <div className="card"><div className="cardhead"><div><h2>{title}</h2><p className="muted">{activePoc?`Selected POC: ${activePoc.poc_code}`:'Select or create a POC.'}</p></div></div>{filtered.length?<div className="dataList">{filtered.map(r=><div className="dataitem" key={r.id}><div><b>{r.test_case||r.checklist_item||r.metric||r.customer_name||r.customer_representative||'Record'}</b><span>{r.actual_result||r.measured_result||r.evidence||r.industry||r.status||'—'}</span></div>{r.status&&section!=='environment'&&section!=='signoff'?<select value={r.status} onChange={e=>update(section==='entry'?'entry_checklist':section==='exit'?'exit_checklist':section==='tests'?'poc_tests':section==='metrics'?'poc_metrics':'customers',r.id,{status:e.target.value})}><option>Not Started</option><option>In Progress</option><option>Completed</option><option>Blocked</option><option>Not Tested</option><option>Open</option><option>Resolved</option></select>:null}</div>)}</div>:<div className="empty">No records yet. This section will populate as you complete the POC.</div>}</div>}
function FormCard({title,onSubmit,children}){return <form className="card form" onSubmit={onSubmit}><h2>{title}</h2>{children}</form>}
function Input({label,value,onChange,type='text',placeholder=''}){return <label className="field"><span>{label}</span><input type={type} value={value??''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}){return <label className="field"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function ListCard({title,rows,fields}){return <div className="card"><h2>{title}</h2>{rows.length?rows.map(r=><div className="tableRow" key={r.id}>{fields.map(f=><span key={f}>{r[f]||'—'}</span>)}</div>):<div className="empty">No records yet.</div>}</div>}
